#############################################################################
# Makefile for building: simpleImageProcessor5
# Generated by qmake (2.01a) (Qt 4.7.4) on: Wed Nov 16 18:20:31 2011
# Project:  simpleImageProcessor5.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile simpleImageProcessor5.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/home/afczero/College_Subjects/Digital_Image_Processing/fftw-3.3/ -lfftw3 -lQtGui -lQtCore -lpthread -L/home/afczero/College_Subjects/Digital_Image_Processing/fftw-3.3//.libs 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CentralArea.cpp \
		Histogram.cpp \
		Image.cpp \
		Information.cpp \
		Main.cpp \
		Random.cpp \
		SimpleDIP.cpp \
		ToolTabs.cpp \
		Dialogs.cpp moc_CentralArea.cpp \
		moc_Histogram.cpp \
		moc_Image.cpp \
		moc_Information.cpp \
		moc_SimpleDIP.cpp \
		moc_ToolTabs.cpp \
		moc_Dialogs.cpp
OBJECTS       = CentralArea.o \
		Histogram.o \
		Image.o \
		Information.o \
		Main.o \
		Random.o \
		SimpleDIP.o \
		ToolTabs.o \
		Dialogs.o \
		moc_CentralArea.o \
		moc_Histogram.o \
		moc_Image.o \
		moc_Information.o \
		moc_SimpleDIP.o \
		moc_ToolTabs.o \
		moc_Dialogs.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		simpleImageProcessor5.pro
QMAKE_TARGET  = simpleImageProcessor5
DESTDIR       = 
TARGET        = simpleImageProcessor5

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: simpleImageProcessor5.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile simpleImageProcessor5.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile simpleImageProcessor5.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/simpleImageProcessor51.0.0 || $(MKDIR) .tmp/simpleImageProcessor51.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/simpleImageProcessor51.0.0/ && $(COPY_FILE) --parents CentralArea.h Histogram.h Image.h Information.h Random.h SimpleDIP.h ToolTabs.h Dialogs.h .tmp/simpleImageProcessor51.0.0/ && $(COPY_FILE) --parents CentralArea.cpp Histogram.cpp Image.cpp Information.cpp Main.cpp Random.cpp SimpleDIP.cpp ToolTabs.cpp Dialogs.cpp .tmp/simpleImageProcessor51.0.0/ && (cd `dirname .tmp/simpleImageProcessor51.0.0` && $(TAR) simpleImageProcessor51.0.0.tar simpleImageProcessor51.0.0 && $(COMPRESS) simpleImageProcessor51.0.0.tar) && $(MOVE) `dirname .tmp/simpleImageProcessor51.0.0`/simpleImageProcessor51.0.0.tar.gz . && $(DEL_FILE) -r .tmp/simpleImageProcessor51.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_CentralArea.cpp moc_Histogram.cpp moc_Image.cpp moc_Information.cpp moc_SimpleDIP.cpp moc_ToolTabs.cpp moc_Dialogs.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_CentralArea.cpp moc_Histogram.cpp moc_Image.cpp moc_Information.cpp moc_SimpleDIP.cpp moc_ToolTabs.cpp moc_Dialogs.cpp
moc_CentralArea.cpp: Image.h \
		Random.h \
		CentralArea.h
	/usr/bin/moc $(DEFINES) $(INCPATH) CentralArea.h -o moc_CentralArea.cpp

moc_Histogram.cpp: Histogram.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Histogram.h -o moc_Histogram.cpp

moc_Image.cpp: Random.h \
		Image.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Image.h -o moc_Image.cpp

moc_Information.cpp: Histogram.h \
		Information.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Information.h -o moc_Information.cpp

moc_SimpleDIP.cpp: CentralArea.h \
		Image.h \
		Random.h \
		ToolTabs.h \
		Information.h \
		Histogram.h \
		Dialogs.h \
		SimpleDIP.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SimpleDIP.h -o moc_SimpleDIP.cpp

moc_ToolTabs.cpp: ToolTabs.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ToolTabs.h -o moc_ToolTabs.cpp

moc_Dialogs.cpp: Dialogs.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Dialogs.h -o moc_Dialogs.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

CentralArea.o: CentralArea.cpp CentralArea.h \
		Image.h \
		Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CentralArea.o CentralArea.cpp

Histogram.o: Histogram.cpp Histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Histogram.o Histogram.cpp

Image.o: Image.cpp Image.h \
		Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Image.o Image.cpp

Information.o: Information.cpp Information.h \
		Histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Information.o Information.cpp

Main.o: Main.cpp SimpleDIP.h \
		CentralArea.h \
		Image.h \
		Random.h \
		ToolTabs.h \
		Information.h \
		Histogram.h \
		Dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

Random.o: Random.cpp Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Random.o Random.cpp

SimpleDIP.o: SimpleDIP.cpp SimpleDIP.h \
		CentralArea.h \
		Image.h \
		Random.h \
		ToolTabs.h \
		Information.h \
		Histogram.h \
		Dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimpleDIP.o SimpleDIP.cpp

ToolTabs.o: ToolTabs.cpp ToolTabs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ToolTabs.o ToolTabs.cpp

Dialogs.o: Dialogs.cpp Dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dialogs.o Dialogs.cpp

moc_CentralArea.o: moc_CentralArea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CentralArea.o moc_CentralArea.cpp

moc_Histogram.o: moc_Histogram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Histogram.o moc_Histogram.cpp

moc_Image.o: moc_Image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Image.o moc_Image.cpp

moc_Information.o: moc_Information.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Information.o moc_Information.cpp

moc_SimpleDIP.o: moc_SimpleDIP.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SimpleDIP.o moc_SimpleDIP.cpp

moc_ToolTabs.o: moc_ToolTabs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ToolTabs.o moc_ToolTabs.cpp

moc_Dialogs.o: moc_Dialogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Dialogs.o moc_Dialogs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

