#############################################################################
# Makefile for building: Graphic-Processor
# Generated by qmake (2.01a) (Qt 4.7.4) on: Tue Sep 25 15:53:38 2012
# Project:  Graphic-Processor.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Graphic-Processor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Isrc/ui -Isrc/algo -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Main.cpp \
		src/SimpleDIP.cpp \
		src/algo/Image.cpp \
		src/algo/ImageMatching.cpp \
		src/algo/Random.cpp \
		src/ui/CentralArea.cpp \
		src/ui/Dialogs.cpp \
		src/ui/Histogram.cpp \
		src/ui/Information.cpp \
		src/ui/ToolTabs.cpp moc_SimpleDIP.cpp \
		moc_Image.cpp \
		moc_ImageMatching.cpp \
		moc_CentralArea.cpp \
		moc_Dialogs.cpp \
		moc_Histogram.cpp \
		moc_Information.cpp \
		moc_ToolTabs.cpp
OBJECTS       = Main.o \
		SimpleDIP.o \
		Image.o \
		ImageMatching.o \
		Random.o \
		CentralArea.o \
		Dialogs.o \
		Histogram.o \
		Information.o \
		ToolTabs.o \
		moc_SimpleDIP.o \
		moc_Image.o \
		moc_ImageMatching.o \
		moc_CentralArea.o \
		moc_Dialogs.o \
		moc_Histogram.o \
		moc_Information.o \
		moc_ToolTabs.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Graphic-Processor.pro
QMAKE_TARGET  = Graphic-Processor
DESTDIR       = 
TARGET        = Graphic-Processor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Graphic-Processor.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Graphic-Processor.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Graphic-Processor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Graphic-Processor1.0.0 || $(MKDIR) .tmp/Graphic-Processor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Graphic-Processor1.0.0/ && $(COPY_FILE) --parents src/SimpleDIP.h src/algo/Image.h src/algo/ImageMatching.h src/algo/Random.h src/ui/CentralArea.h src/ui/Dialogs.h src/ui/Histogram.h src/ui/Information.h src/ui/ToolTabs.h .tmp/Graphic-Processor1.0.0/ && $(COPY_FILE) --parents src/Main.cpp src/SimpleDIP.cpp src/algo/Image.cpp src/algo/ImageMatching.cpp src/algo/Random.cpp src/ui/CentralArea.cpp src/ui/Dialogs.cpp src/ui/Histogram.cpp src/ui/Information.cpp src/ui/ToolTabs.cpp .tmp/Graphic-Processor1.0.0/ && (cd `dirname .tmp/Graphic-Processor1.0.0` && $(TAR) Graphic-Processor1.0.0.tar Graphic-Processor1.0.0 && $(COMPRESS) Graphic-Processor1.0.0.tar) && $(MOVE) `dirname .tmp/Graphic-Processor1.0.0`/Graphic-Processor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Graphic-Processor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_SimpleDIP.cpp moc_Image.cpp moc_ImageMatching.cpp moc_CentralArea.cpp moc_Dialogs.cpp moc_Histogram.cpp moc_Information.cpp moc_ToolTabs.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SimpleDIP.cpp moc_Image.cpp moc_ImageMatching.cpp moc_CentralArea.cpp moc_Dialogs.cpp moc_Histogram.cpp moc_Information.cpp moc_ToolTabs.cpp
moc_SimpleDIP.cpp: src/ui/CentralArea.h \
		src/algo/Image.h \
		src/algo/Random.h \
		src/ui/ToolTabs.h \
		src/ui/Information.h \
		src/ui/Histogram.h \
		src/ui/Dialogs.h \
		src/algo/ImageMatching.h \
		src/SimpleDIP.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/SimpleDIP.h -o moc_SimpleDIP.cpp

moc_Image.cpp: src/algo/Random.h \
		src/algo/Image.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/algo/Image.h -o moc_Image.cpp

moc_ImageMatching.cpp: src/ui/CentralArea.h \
		src/algo/Image.h \
		src/algo/Random.h \
		src/ui/ToolTabs.h \
		src/ui/Information.h \
		src/ui/Histogram.h \
		src/ui/Dialogs.h \
		src/algo/ImageMatching.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/algo/ImageMatching.h -o moc_ImageMatching.cpp

moc_CentralArea.cpp: src/algo/Image.h \
		src/algo/Random.h \
		src/ui/CentralArea.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/CentralArea.h -o moc_CentralArea.cpp

moc_Dialogs.cpp: src/ui/Dialogs.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/Dialogs.h -o moc_Dialogs.cpp

moc_Histogram.cpp: src/ui/Histogram.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/Histogram.h -o moc_Histogram.cpp

moc_Information.cpp: src/ui/Histogram.h \
		src/ui/Information.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/Information.h -o moc_Information.cpp

moc_ToolTabs.cpp: src/algo/Image.h \
		src/algo/Random.h \
		src/ui/ToolTabs.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/ToolTabs.h -o moc_ToolTabs.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Main.o: src/Main.cpp src/SimpleDIP.h \
		src/ui/CentralArea.h \
		src/algo/Image.h \
		src/algo/Random.h \
		src/ui/ToolTabs.h \
		src/ui/Information.h \
		src/ui/Histogram.h \
		src/ui/Dialogs.h \
		src/algo/ImageMatching.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o src/Main.cpp

SimpleDIP.o: src/SimpleDIP.cpp src/SimpleDIP.h \
		src/ui/CentralArea.h \
		src/algo/Image.h \
		src/algo/Random.h \
		src/ui/ToolTabs.h \
		src/ui/Information.h \
		src/ui/Histogram.h \
		src/ui/Dialogs.h \
		src/algo/ImageMatching.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimpleDIP.o src/SimpleDIP.cpp

Image.o: src/algo/Image.cpp src/algo/Image.h \
		src/algo/Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Image.o src/algo/Image.cpp

ImageMatching.o: src/algo/ImageMatching.cpp src/algo/ImageMatching.h \
		src/ui/CentralArea.h \
		src/algo/Image.h \
		src/algo/Random.h \
		src/ui/ToolTabs.h \
		src/ui/Information.h \
		src/ui/Histogram.h \
		src/ui/Dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageMatching.o src/algo/ImageMatching.cpp

Random.o: src/algo/Random.cpp src/algo/Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Random.o src/algo/Random.cpp

CentralArea.o: src/ui/CentralArea.cpp src/ui/CentralArea.h \
		src/algo/Image.h \
		src/algo/Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CentralArea.o src/ui/CentralArea.cpp

Dialogs.o: src/ui/Dialogs.cpp src/ui/Dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dialogs.o src/ui/Dialogs.cpp

Histogram.o: src/ui/Histogram.cpp src/ui/Histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Histogram.o src/ui/Histogram.cpp

Information.o: src/ui/Information.cpp src/ui/Information.h \
		src/ui/Histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Information.o src/ui/Information.cpp

ToolTabs.o: src/ui/ToolTabs.cpp src/ui/ToolTabs.h \
		src/algo/Image.h \
		src/algo/Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ToolTabs.o src/ui/ToolTabs.cpp

moc_SimpleDIP.o: moc_SimpleDIP.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SimpleDIP.o moc_SimpleDIP.cpp

moc_Image.o: moc_Image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Image.o moc_Image.cpp

moc_ImageMatching.o: moc_ImageMatching.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageMatching.o moc_ImageMatching.cpp

moc_CentralArea.o: moc_CentralArea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CentralArea.o moc_CentralArea.cpp

moc_Dialogs.o: moc_Dialogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Dialogs.o moc_Dialogs.cpp

moc_Histogram.o: moc_Histogram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Histogram.o moc_Histogram.cpp

moc_Information.o: moc_Information.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Information.o moc_Information.cpp

moc_ToolTabs.o: moc_ToolTabs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ToolTabs.o moc_ToolTabs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

